using System;
using UnityEngine;

/// <summary>
/// Stores one per-element gameplay behaviour block used by default player bullet elemental payloads.
/// /params none.
/// /returns none.
/// </summary>
[Serializable]
public sealed class ElementBulletSettings
{
    #region Fields

    #region Serialized Fields
    [Header("Element Behaviour")]
    [Tooltip("Gameplay effect generated by this bullet element.")]
    [SerializeField] private ElementalEffectKind effectKind = ElementalEffectKind.Dots;

    [Tooltip("How elemental stacks behave before or at threshold.")]
    [SerializeField] private ElementalProcMode procMode = ElementalProcMode.ThresholdOnly;

    [Tooltip("How new stacks behave while the same element proc is already active.")]
    [SerializeField] private ElementalProcReapplyMode reapplyMode = ElementalProcReapplyMode.AccumulateStacks;

    [Tooltip("Elemental stacks applied by each valid projectile hit.")]
    [SerializeField] private float stacksPerHit = 1f;

    [Tooltip("Stacks required to trigger the full elemental proc.")]
    [SerializeField] private float procThresholdStacks = 5f;

    [Tooltip("Maximum stack amount stored on a target for this bullet element.")]
    [SerializeField] private float maximumStacks = 20f;

    [Tooltip("Stacks removed per second while the target is not refreshed.")]
    [SerializeField] private float stackDecayPerSecond = 1f;

    [Tooltip("When enabled, threshold procs consume the configured threshold amount of stacks.")]
    [SerializeField] private bool consumeStacksOnProc;

    [Header("Dots Effect")]
    [Tooltip("Damage dealt by each dots tick when the elemental effect kind is Dots.")]
    [SerializeField] private float dotDamagePerTick = 4f;

    [Tooltip("Seconds between two consecutive dots ticks.")]
    [SerializeField] private float dotTickInterval = 0.5f;

    [Tooltip("Duration in seconds of the dots proc.")]
    [SerializeField] private float dotDurationSeconds = 2f;

    [Header("Impediment Effect")]
    [Tooltip("Slow percentage added by each stack in progressive impediment mode.")]
    [SerializeField] private float impedimentSlowPercentPerStack = 10f;

    [Tooltip("Slow percentage applied when the impediment threshold proc triggers.")]
    [SerializeField] private float impedimentProcSlowPercent = 50f;

    [Tooltip("Maximum total slow percentage allowed for this impediment effect.")]
    [SerializeField] private float impedimentMaxSlowPercent = 100f;

    [Tooltip("Duration in seconds of the impediment threshold proc.")]
    [SerializeField] private float impedimentDurationSeconds = 2f;
    #endregion

    #endregion

    #region Properties
    public ElementalEffectKind EffectKind
    {
        get
        {
            return effectKind;
        }
    }

    public ElementalProcMode ProcMode
    {
        get
        {
            return procMode;
        }
    }

    public ElementalProcReapplyMode ReapplyMode
    {
        get
        {
            return reapplyMode;
        }
    }

    public float StacksPerHit
    {
        get
        {
            return stacksPerHit;
        }
    }

    public float ProcThresholdStacks
    {
        get
        {
            return procThresholdStacks;
        }
    }

    public float MaximumStacks
    {
        get
        {
            return maximumStacks;
        }
    }

    public float StackDecayPerSecond
    {
        get
        {
            return stackDecayPerSecond;
        }
    }

    public bool ConsumeStacksOnProc
    {
        get
        {
            return consumeStacksOnProc;
        }
    }

    public float DotDamagePerTick
    {
        get
        {
            return dotDamagePerTick;
        }
    }

    public float DotTickInterval
    {
        get
        {
            return dotTickInterval;
        }
    }

    public float DotDurationSeconds
    {
        get
        {
            return dotDurationSeconds;
        }
    }

    public float ImpedimentSlowPercentPerStack
    {
        get
        {
            return impedimentSlowPercentPerStack;
        }
    }

    public float ImpedimentProcSlowPercent
    {
        get
        {
            return impedimentProcSlowPercent;
        }
    }

    public float ImpedimentMaxSlowPercent
    {
        get
        {
            return impedimentMaxSlowPercent;
        }
    }

    public float ImpedimentDurationSeconds
    {
        get
        {
            return impedimentDurationSeconds;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Copies every authored gameplay value from another behaviour block while preserving this instance allocation.
    /// /params source Source behaviour block.
    /// /returns void.
    /// </summary>
    public void CopyFrom(ElementBulletSettings source)
    {
        if (source == null)
            return;

        effectKind = source.effectKind;
        procMode = source.procMode;
        reapplyMode = source.reapplyMode;
        stacksPerHit = source.stacksPerHit;
        procThresholdStacks = source.procThresholdStacks;
        maximumStacks = source.maximumStacks;
        stackDecayPerSecond = source.stackDecayPerSecond;
        consumeStacksOnProc = source.consumeStacksOnProc;
        dotDamagePerTick = source.dotDamagePerTick;
        dotTickInterval = source.dotTickInterval;
        dotDurationSeconds = source.dotDurationSeconds;
        impedimentSlowPercentPerStack = source.impedimentSlowPercentPerStack;
        impedimentProcSlowPercent = source.impedimentProcSlowPercent;
        impedimentMaxSlowPercent = source.impedimentMaxSlowPercent;
        impedimentDurationSeconds = source.impedimentDurationSeconds;
    }
    #endregion

    #region Validation
    /// <summary>
    /// Keeps the behaviour block available to legacy validation paths without mutating authored gameplay values.
    /// /params none.
    /// /returns void.
    /// </summary>
    public void Validate()
    {
    }
    #endregion

    #endregion
}
