using System;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public sealed class ProjectileSizePassiveToolData
{
    #region Fields

    #region Serialized Fields
    [Header("Projectile Size Passive")]
    [Tooltip("Multiplier applied to projectile transform scale and collision radius. 1 keeps default size.")]
    [SerializeField] private float projectileSizeMultiplier = 1f;

    [Tooltip("Multiplier applied to projectile damage. 1 keeps default damage.")]
    [SerializeField] private float damageMultiplier = 1f;

    [Tooltip("Multiplier applied to projectile speed. 1 keeps default speed.")]
    [SerializeField] private float speedMultiplier = 1f;

    [Tooltip("Multiplier applied to projectile lifetime in seconds. 1 keeps default temporal lifetime.")]
    [SerializeField] private float lifetimeSecondsMultiplier = 1f;

    [Tooltip("Multiplier applied to projectile max range distance. 1 keeps default distance lifetime.")]
    [SerializeField] private float lifetimeRangeMultiplier = 1f;
    #endregion

    #endregion

    #region Properties
    public float ProjectileSizeMultiplier
    {
        get
        {
            return projectileSizeMultiplier;
        }
    }

    public float DamageMultiplier
    {
        get
        {
            return damageMultiplier;
        }
    }

    public float SpeedMultiplier
    {
        get
        {
            return speedMultiplier;
        }
    }

    public float LifetimeSecondsMultiplier
    {
        get
        {
            return lifetimeSecondsMultiplier;
        }
    }

    public float LifetimeRangeMultiplier
    {
        get
        {
            return lifetimeRangeMultiplier;
        }
    }
    #endregion

    #region Methods

    #region Validation
    public void Validate()
    {
        if (projectileSizeMultiplier < 0.01f)
            projectileSizeMultiplier = 0.01f;

        if (damageMultiplier < 0f)
            damageMultiplier = 0f;

        if (speedMultiplier < 0f)
            speedMultiplier = 0f;

        if (lifetimeSecondsMultiplier < 0f)
            lifetimeSecondsMultiplier = 0f;

        if (lifetimeRangeMultiplier < 0f)
            lifetimeRangeMultiplier = 0f;
    }
    #endregion

    #endregion
}

[Serializable]
public sealed class ElementalEffectDefinitionData
{
    #region Fields

    #region Serialized Fields
    [Header("Element")]
    [Tooltip("Element identifier used by this payload.")]
    [SerializeField] private ElementType elementType = ElementType.Fire;

    [Tooltip("Gameplay effect generated by this element.")]
    [SerializeField] private ElementalEffectKind effectKind = ElementalEffectKind.Dots;

    [Tooltip("How stacks apply effect strength before threshold.")]
    [SerializeField] private ElementalProcMode procMode = ElementalProcMode.ThresholdOnly;

    [Tooltip("How incoming stacks behave while this element proc is already active on the same target.")]
    [SerializeField] private ElementalProcReapplyMode reapplyMode = ElementalProcReapplyMode.AccumulateStacks;

    [Tooltip("Stacks required to trigger full element proc.")]
    [SerializeField] private float procThresholdStacks = 5f;

    [Tooltip("Maximum stack amount kept on a target for this element.")]
    [SerializeField] private float maximumStacks = 20f;

    [Tooltip("Stacks removed per second when the target is not refreshed.")]
    [SerializeField] private float stackDecayPerSecond = 1f;

    [Tooltip("When enabled, stacks are consumed when threshold proc triggers.")]
    [SerializeField] private bool consumeStacksOnProc;

    [Header("Dots Effect")]
    [Tooltip("Damage applied every tick when Dots effect is active.")]
    [SerializeField] private float dotDamagePerTick = 4f;

    [Tooltip("Seconds between two consecutive dot ticks.")]
    [SerializeField] private float dotTickInterval = 0.5f;

    [Tooltip("Duration in seconds of the dots payload when proc occurs.")]
    [SerializeField] private float dotDurationSeconds = 2f;

    [Header("Impediment Effect")]
    [Tooltip("Slow percentage gained per stack in progressive mode. Example: 10 means 10%.")]
    [SerializeField] private float impedimentSlowPercentPerStack = 10f;

    [Tooltip("Slow percentage applied when threshold proc occurs. Example: 50 means 50%.")]
    [SerializeField] private float impedimentProcSlowPercent = 50f;

    [Tooltip("Maximum total slow percentage cap. 100 means complete immobilization.")]
    [SerializeField] private float impedimentMaxSlowPercent = 100f;

    [Tooltip("Duration in seconds of threshold impediment proc.")]
    [SerializeField] private float impedimentDurationSeconds = 2f;
    #endregion

    #endregion

    #region Properties
    public ElementType ElementType
    {
        get
        {
            return elementType;
        }
    }

    public ElementalEffectKind EffectKind
    {
        get
        {
            return effectKind;
        }
    }

    public ElementalProcMode ProcMode
    {
        get
        {
            return procMode;
        }
    }

    public ElementalProcReapplyMode ReapplyMode
    {
        get
        {
            return reapplyMode;
        }
    }

    public float ProcThresholdStacks
    {
        get
        {
            return procThresholdStacks;
        }
    }

    public float MaximumStacks
    {
        get
        {
            return maximumStacks;
        }
    }

    public float StackDecayPerSecond
    {
        get
        {
            return stackDecayPerSecond;
        }
    }

    public bool ConsumeStacksOnProc
    {
        get
        {
            return consumeStacksOnProc;
        }
    }

    public float DotDamagePerTick
    {
        get
        {
            return dotDamagePerTick;
        }
    }

    public float DotTickInterval
    {
        get
        {
            return dotTickInterval;
        }
    }

    public float DotDurationSeconds
    {
        get
        {
            return dotDurationSeconds;
        }
    }

    public float ImpedimentSlowPercentPerStack
    {
        get
        {
            return impedimentSlowPercentPerStack;
        }
    }

    public float ImpedimentProcSlowPercent
    {
        get
        {
            return impedimentProcSlowPercent;
        }
    }

    public float ImpedimentMaxSlowPercent
    {
        get
        {
            return impedimentMaxSlowPercent;
        }
    }

    public float ImpedimentDurationSeconds
    {
        get
        {
            return impedimentDurationSeconds;
        }
    }
    #endregion

    #region Methods

    #region Validation
    public void Validate()
    {
        if (procThresholdStacks < 0.1f)
            procThresholdStacks = 0.1f;

        if (maximumStacks < 0.1f)
            maximumStacks = 0.1f;

        if (maximumStacks < procThresholdStacks)
            maximumStacks = procThresholdStacks;

        if (stackDecayPerSecond < 0f)
            stackDecayPerSecond = 0f;

        if (dotDamagePerTick < 0f)
            dotDamagePerTick = 0f;

        if (dotTickInterval < 0.01f)
            dotTickInterval = 0.01f;

        if (dotDurationSeconds < 0.05f)
            dotDurationSeconds = 0.05f;

        if (impedimentSlowPercentPerStack < 0f)
            impedimentSlowPercentPerStack = 0f;

        if (impedimentProcSlowPercent < 0f)
            impedimentProcSlowPercent = 0f;

        if (impedimentMaxSlowPercent < 0f)
            impedimentMaxSlowPercent = 0f;

        if (impedimentMaxSlowPercent > 100f)
            impedimentMaxSlowPercent = 100f;

        if (impedimentProcSlowPercent > impedimentMaxSlowPercent)
            impedimentProcSlowPercent = impedimentMaxSlowPercent;

        if (impedimentDurationSeconds < 0.05f)
            impedimentDurationSeconds = 0.05f;
    }
    #endregion

    #endregion
}

[Serializable]
public sealed class ElementalProjectilesPassiveToolData
{
    #region Fields

    #region Serialized Fields
    [Header("Elemental Projectiles")]
    [Tooltip("Elemental effect payload applied when a projectile hits an enemy.")]
    [SerializeField] private ElementalEffectDefinitionData effectData = new ElementalEffectDefinitionData();

    [Tooltip("Stacks added to the hit enemy by each projectile impact.")]
    [SerializeField] private float stacksPerHit = 1f;
    #endregion

    #endregion

    #region Properties
    public ElementalEffectDefinitionData EffectData
    {
        get
        {
            return effectData;
        }
    }

    public float StacksPerHit
    {
        get
        {
            return stacksPerHit;
        }
    }
    #endregion

    #region Methods

    #region Validation
    public void Validate()
    {
        if (effectData == null)
            effectData = new ElementalEffectDefinitionData();

        effectData.Validate();

        if (stacksPerHit < 0f)
            stacksPerHit = 0f;
    }
    #endregion

    #endregion
}

[Serializable]
public sealed class PerfectCirclePassiveToolData
{
    #region Fields

    #region Serialized Fields
    [Header("Perfect Circle")]
    [Tooltip("Entry speed while projectiles move away from the player before full orbit.")]
    [SerializeField] private float radialEntrySpeed = 12f;

    [Tooltip("Tangential speed used while projectiles orbit around the player.")]
    [SerializeField] private float orbitalSpeed = 8f;

    [Tooltip("Minimum orbit radius reached during rhythmic orbit pulsation.")]
    [SerializeField] private float orbitRadiusMin = 4f;

    [Tooltip("Maximum orbit radius reached during rhythmic orbit pulsation.")]
    [SerializeField] private float orbitRadiusMax = 6f;

    [Tooltip("Frequency in hertz used to expand and retract orbit radius rhythmically.")]
    [SerializeField] private float orbitPulseFrequency = 0.7f;

    [Tooltip("Ratio of target radius used as entry threshold before projectile switches to orbit mode.")]
    [SerializeField] private float orbitEntryRatio = 0.9f;

    [Tooltip("Seconds used to blend from radial motion to orbit motion.")]
    [SerializeField] private float orbitBlendDuration = 0.3f;

    [Tooltip("Vertical offset from player origin used for orbit simulation.")]
    [SerializeField] private float heightOffset;

    [Tooltip("Golden-angle step in degrees used to distribute orbit angles for consecutive spawns.")]
    [SerializeField] private float goldenAngleDegrees = 137.5f;
    #endregion

    #endregion

    #region Properties
    public float RadialEntrySpeed
    {
        get
        {
            return radialEntrySpeed;
        }
    }

    public float OrbitalSpeed
    {
        get
        {
            return orbitalSpeed;
        }
    }

    public float OrbitRadiusMin
    {
        get
        {
            return orbitRadiusMin;
        }
    }

    public float OrbitRadiusMax
    {
        get
        {
            return orbitRadiusMax;
        }
    }

    public float OrbitPulseFrequency
    {
        get
        {
            return orbitPulseFrequency;
        }
    }

    public float OrbitEntryRatio
    {
        get
        {
            return orbitEntryRatio;
        }
    }

    public float OrbitBlendDuration
    {
        get
        {
            return orbitBlendDuration;
        }
    }

    public float HeightOffset
    {
        get
        {
            return heightOffset;
        }
    }

    public float GoldenAngleDegrees
    {
        get
        {
            return goldenAngleDegrees;
        }
    }
    #endregion

    #region Methods

    #region Validation
    public void Validate()
    {
        if (radialEntrySpeed < 0f)
            radialEntrySpeed = 0f;

        if (orbitalSpeed < 0f)
            orbitalSpeed = 0f;

        if (orbitRadiusMin < 0f)
            orbitRadiusMin = 0f;

        if (orbitRadiusMax < 0f)
            orbitRadiusMax = 0f;

        if (orbitRadiusMax < orbitRadiusMin)
            orbitRadiusMax = orbitRadiusMin;

        if (orbitPulseFrequency < 0f)
            orbitPulseFrequency = 0f;

        orbitEntryRatio = Mathf.Clamp01(orbitEntryRatio);

        if (orbitBlendDuration < 0f)
            orbitBlendDuration = 0f;

        if (goldenAngleDegrees < 0f)
            goldenAngleDegrees = Mathf.Abs(goldenAngleDegrees);
    }
    #endregion

    #endregion
}
