using System.Collections.Generic;
using Unity.Entities;
using Unity.Mathematics;
using UnityEngine;

/// <summary>
/// Resolves authored Laser Beam endpoint visuals and converts gameplay lanes into render-time ribbon data.
/// /params None.
/// /returns None.
/// </summary>
internal static class PlayerLaserBeamPresentationRuntimeGeometryUtility
{
    #region Constants
    private const int MaximumRibbonPointsPerLane = 2048;
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Resolves the authored source particle prefab mapped to the requested cap shape.
    /// /params sourceVariants Baked source variant buffer.
    /// /params shape Runtime source cap-shape selector.
    /// /returns Matching prefab when present, otherwise null.
    /// </summary>
    public static GameObject ResolveSourcePrefab(DynamicBuffer<PlayerLaserBeamSourceVariantElement> sourceVariants,
                                                 LaserBeamCapShape shape)
    {
        for (int variantIndex = 0; variantIndex < sourceVariants.Length; variantIndex++)
        {
            PlayerLaserBeamSourceVariantElement variant = sourceVariants[variantIndex];

            if (variant.Shape != shape)
                continue;

            return variant.Prefab.Value;
        }

        return null;
    }

    /// <summary>
    /// Resolves the authored impact particle prefab mapped to the requested cap shape.
    /// /params impactVariants Baked impact variant buffer.
    /// /params shape Runtime impact cap-shape selector.
    /// /returns Matching prefab when present, otherwise null.
    /// </summary>
    public static GameObject ResolveImpactPrefab(DynamicBuffer<PlayerLaserBeamImpactVariantElement> impactVariants,
                                                 LaserBeamCapShape shape)
    {
        for (int variantIndex = 0; variantIndex < impactVariants.Length; variantIndex++)
        {
            PlayerLaserBeamImpactVariantElement variant = impactVariants[variantIndex];

            if (variant.Shape != shape)
                continue;

            return variant.Prefab.Value;
        }

        return null;
    }

    /// <summary>
    /// Resolves the flow and storm colors used by the current beam from the baked visual preset buffer.
    /// /params visualPresetId Runtime visual preset selector.
    /// /params visualPresetBuffer Baked visual preset buffer.
    /// /returns Resolved colors converted back to managed Unity colors.
    /// </summary>
    public static PlayerLaserBeamResolvedPalette ResolvePalette(int visualPresetId,
                                                                DynamicBuffer<PlayerLaserBeamVisualPresetElement> visualPresetBuffer)
    {
        for (int presetIndex = 0; presetIndex < visualPresetBuffer.Length; presetIndex++)
        {
            PlayerLaserBeamVisualPresetElement visualPresetElement = visualPresetBuffer[presetIndex];

            if (visualPresetElement.VisualPresetId != visualPresetId)
                continue;

            return new PlayerLaserBeamResolvedPalette
            {
                CoreColor = ToColor(visualPresetElement.CoreColor),
                FlowColor = ToColor(visualPresetElement.FlowColor),
                StormColor = ToColor(visualPresetElement.StormColor),
                ContactColor = ToColor(visualPresetElement.ContactColor)
            };
        }

        PlayerLaserBeamVisualDefaultsUtility.ResolveDefaultPreset(visualPresetId,
                                                                  out string _,
                                                                  out Color coreColor,
                                                                  out Color flowColor,
                                                                  out Color stormColor,
                                                                  out Color contactColor);
        return new PlayerLaserBeamResolvedPalette
        {
            CoreColor = coreColor,
            FlowColor = flowColor,
            StormColor = stormColor,
            ContactColor = contactColor
        };
    }

    /// <summary>
    /// Rebuilds render-time ribbon points, lane visuals, and endpoint data from the authoritative gameplay lane buffer.
    /// /params laserBeamLanes Gameplay lane buffer generated by simulation.
    /// /params visualConfig Shared visual config used to resample curved paths.
    /// /params ribbonPoints Mutable destination list for the resampled ribbon points.
    /// /params laneVisuals Mutable destination list for per-lane ribbon metadata.
    /// /params laneEndpoints Mutable destination list for per-lane source and impact anchors.
    /// /returns True when at least one lane visual and endpoint were produced.
    /// </summary>
    public static bool BuildLaneVisualData(DynamicBuffer<PlayerLaserBeamLaneElement> laserBeamLanes,
                                           in PlayerLaserBeamVisualConfig visualConfig,
                                           in LaserBeamPassiveConfig laserBeamConfig,
                                           List<PlayerLaserBeamRibbonPoint> ribbonPoints,
                                           List<PlayerLaserBeamLaneVisual> laneVisuals,
                                           List<PlayerLaserBeamLaneEndpoint> laneEndpoints)
    {
        ribbonPoints.Clear();
        laneVisuals.Clear();
        laneEndpoints.Clear();

        if (laserBeamLanes.Length <= 0)
            return false;

        int segmentIndex = 0;

        while (segmentIndex < laserBeamLanes.Length)
        {
            PlayerLaserBeamLaneElement firstSegment = laserBeamLanes[segmentIndex];
            int laneSegmentStartIndex = segmentIndex;
            int laneSegmentEndIndex = ResolveLaneSegmentEndIndex(laserBeamLanes, laneSegmentStartIndex);
            int lanePointStartIndex = ribbonPoints.Count;
            float laneLength = 0f;
            float adaptiveMaximumSegmentLength = ResolveAdaptiveMaximumRibbonSegmentLength(in visualConfig,
                                                                                           laserBeamLanes,
                                                                                           laneSegmentStartIndex,
                                                                                           laneSegmentEndIndex,
                                                                                           laserBeamConfig.SourceOffset);
            PlayerLaserBeamLaneEndpoint endpoint = new PlayerLaserBeamLaneEndpoint
            {
                LaneIndex = firstSegment.LaneIndex,
                MuzzlePoint = LiftPoint(firstSegment.StartPoint, visualConfig.VerticalLift),
                VisibleStartPoint = LiftPoint(firstSegment.StartPoint, visualConfig.VerticalLift),
                StartDirection = firstSegment.Direction,
                StartWidth = firstSegment.VisualWidth,
                EndPoint = LiftPoint(firstSegment.EndPoint, visualConfig.VerticalLift),
                EndDirection = firstSegment.Direction,
                EndWidth = firstSegment.VisualWidth,
                TerminalNormal = firstSegment.TerminalNormal,
                TerminalBlockedByWall = firstSegment.TerminalBlockedByWall
            };
            float remainingSourceTrim = math.max(0f, laserBeamConfig.SourceOffset);
            bool hasVisibleStartPoint = false;
            int laneSegmentIndex = laneSegmentStartIndex;

            while (laneSegmentIndex < laneSegmentEndIndex)
            {
                PlayerLaserBeamLaneElement segment = laserBeamLanes[laneSegmentIndex];
                float segmentLength = math.max(0f, segment.Length);

                if (segmentLength <= 0f)
                {
                    endpoint.EndPoint = LiftPoint(segment.EndPoint, visualConfig.VerticalLift);
                    endpoint.EndDirection = segment.Direction;
                    endpoint.EndWidth = segment.VisualWidth;
                    endpoint.TerminalNormal = segment.TerminalNormal;
                    endpoint.TerminalBlockedByWall = segment.TerminalBlockedByWall;
                    laneSegmentIndex++;
                    continue;
                }

                float trimmedDistance = math.min(segmentLength, remainingSourceTrim);
                remainingSourceTrim -= trimmedDistance;

                if (trimmedDistance < segmentLength)
                {
                    float trimInterpolation = trimmedDistance / segmentLength;
                    PlayerLaserBeamLaneElement presentationSegment = segment;
                    presentationSegment.StartPoint = math.lerp(segment.StartPoint, segment.EndPoint, trimInterpolation);
                    presentationSegment.Length = segmentLength - trimmedDistance;

                    if (!hasVisibleStartPoint)
                    {
                        endpoint.VisibleStartPoint = LiftPoint(presentationSegment.StartPoint, visualConfig.VerticalLift);
                        endpoint.StartDirection = presentationSegment.Direction;
                        endpoint.StartWidth = presentationSegment.VisualWidth;
                        AddLaneStartPoint(presentationSegment.StartPoint,
                                          presentationSegment.VisualWidth,
                                          visualConfig.VerticalLift,
                                          ribbonPoints);
                        hasVisibleStartPoint = true;
                    }

                    AppendLaneSegmentPoints(presentationSegment,
                                            adaptiveMaximumSegmentLength,
                                            visualConfig.VerticalLift,
                                            ref laneLength,
                                            ribbonPoints);
                }

                endpoint.EndPoint = LiftPoint(segment.EndPoint, visualConfig.VerticalLift);
                endpoint.EndDirection = segment.Direction;
                endpoint.EndWidth = segment.VisualWidth;
                endpoint.TerminalNormal = segment.TerminalNormal;
                endpoint.TerminalBlockedByWall = segment.TerminalBlockedByWall;
                laneSegmentIndex++;
            }

            segmentIndex = laneSegmentEndIndex;

            int pointCount = ribbonPoints.Count - lanePointStartIndex;

            if (pointCount < 2 || !hasVisibleStartPoint)
            {
                ribbonPoints.RemoveRange(lanePointStartIndex, math.max(0, pointCount));
                continue;
            }

            laneVisuals.Add(new PlayerLaserBeamLaneVisual
            {
                LaneIndex = endpoint.LaneIndex,
                PointStartIndex = lanePointStartIndex,
                PointCount = pointCount,
                TotalLength = laneLength,
                StartDirection = endpoint.StartDirection,
                StartWidth = endpoint.StartWidth,
                EndDirection = endpoint.EndDirection,
                EndWidth = endpoint.EndWidth,
                TerminalNormal = endpoint.TerminalNormal,
                TerminalBlockedByWall = endpoint.TerminalBlockedByWall
            });
            laneEndpoints.Add(endpoint);
        }

        return laneVisuals.Count > 0 && laneEndpoints.Count > 0;
    }
    #endregion

    #region Private Methods
    /// <summary>
    /// Adds the first point of a lane before any segment resampling runs.
    /// /params segment First gameplay segment of the lane.
    /// /params verticalLift Shared beam vertical lift.
    /// /params ribbonPoints Mutable destination list for ribbon points.
    /// /returns None.
    /// </summary>
    private static void AddLaneStartPoint(float3 startPoint,
                                          float startWidth,
                                          float verticalLift,
                                          List<PlayerLaserBeamRibbonPoint> ribbonPoints)
    {
        ribbonPoints.Add(new PlayerLaserBeamRibbonPoint
        {
            Position = LiftPoint(startPoint, verticalLift),
            Distance = 0f,
            Width = math.max(0.02f, startWidth)
        });
    }

    /// <summary>
    /// Resamples one gameplay segment into evenly spaced ribbon points while preserving the authoritative path.
    /// /params segment Gameplay segment produced by the simulation path.
    /// /params maximumSegmentLength Maximum spacing allowed between consecutive ribbon points for the current lane.
    /// /params verticalLift Shared beam vertical lift applied to every sampled point.
    /// /params laneLength Mutable accumulated lane length.
    /// /params ribbonPoints Mutable destination list for ribbon points.
    /// /returns None.
    /// </summary>
    private static void AppendLaneSegmentPoints(PlayerLaserBeamLaneElement segment,
                                                float maximumSegmentLength,
                                                float verticalLift,
                                                ref float laneLength,
                                                List<PlayerLaserBeamRibbonPoint> ribbonPoints)
    {
        float segmentLength = math.max(0.001f, segment.Length);
        int sampleCount = math.max(1, (int)math.ceil(segmentLength / maximumSegmentLength));
        float startDistance = laneLength;

        for (int sampleIndex = 1; sampleIndex <= sampleCount; sampleIndex++)
        {
            float interpolation = sampleIndex / (float)sampleCount;
            float3 point = math.lerp(segment.StartPoint, segment.EndPoint, interpolation);
            float pointDistance = startDistance + segmentLength * interpolation;
            ribbonPoints.Add(new PlayerLaserBeamRibbonPoint
            {
                Position = LiftPoint(point, verticalLift),
                Distance = pointDistance,
                Width = math.max(0.02f, segment.VisualWidth)
            });
        }

        laneLength = startDistance + segmentLength;
    }

    /// <summary>
    /// Applies the beam vertical lift to a world-space point.
    /// /params point Unlifted world-space point.
    /// /params verticalLift Shared vertical lift amount.
    /// /returns Lifted world-space point.
    /// </summary>
    private static float3 LiftPoint(float3 point, float verticalLift)
    {
        return new float3(point.x, point.y + verticalLift, point.z);
    }

    /// <summary>
    /// Resolves the exclusive segment end index of the current lane.
    /// /params laserBeamLanes Gameplay lane buffer generated by simulation.
    /// /params laneSegmentStartIndex First segment index belonging to the lane.
    /// /returns Exclusive segment end index of the lane.
    /// </summary>
    private static int ResolveLaneSegmentEndIndex(DynamicBuffer<PlayerLaserBeamLaneElement> laserBeamLanes,
                                                  int laneSegmentStartIndex)
    {
        int laneSegmentEndIndex = laneSegmentStartIndex + 1;
        int laneIndex = laserBeamLanes[laneSegmentStartIndex].LaneIndex;

        while (laneSegmentEndIndex < laserBeamLanes.Length &&
               laserBeamLanes[laneSegmentEndIndex].LaneIndex == laneIndex)
        {
            laneSegmentEndIndex++;
        }

        return laneSegmentEndIndex;
    }

    /// <summary>
    /// Resolves the adaptive segment length used to keep very long beams inside a stable ribbon-point budget.
    /// /params visualConfig Shared visual config used to determine the authored baseline density.
    /// /params laserBeamLanes Gameplay lane buffer generated by simulation.
    /// /params laneSegmentStartIndex First segment index belonging to the lane.
    /// /params laneSegmentEndIndex Exclusive segment end index belonging to the lane.
    /// /params sourceOffset Trim applied at the start of the visible beam.
    /// /returns Adaptive maximum spacing between consecutive ribbon points for the current lane.
    /// </summary>
    private static float ResolveAdaptiveMaximumRibbonSegmentLength(in PlayerLaserBeamVisualConfig visualConfig,
                                                                   DynamicBuffer<PlayerLaserBeamLaneElement> laserBeamLanes,
                                                                   int laneSegmentStartIndex,
                                                                   int laneSegmentEndIndex,
                                                                   float sourceOffset)
    {
        float authoredMaximumSegmentLength = math.max(visualConfig.MinimumSegmentLength, visualConfig.MaximumRibbonSegmentLength);
        float visibleLaneLength = ResolveVisibleLaneLength(laserBeamLanes,
                                                           laneSegmentStartIndex,
                                                           laneSegmentEndIndex,
                                                           sourceOffset);
        float budgetDrivenSegmentLength = visibleLaneLength / math.max(1, MaximumRibbonPointsPerLane - 1);
        return math.max(authoredMaximumSegmentLength, budgetDrivenSegmentLength);
    }

    /// <summary>
    /// Resolves the visible lane length after the authored source trim has been removed.
    /// /params laserBeamLanes Gameplay lane buffer generated by simulation.
    /// /params laneSegmentStartIndex First segment index belonging to the lane.
    /// /params laneSegmentEndIndex Exclusive segment end index belonging to the lane.
    /// /params sourceOffset Trim applied at the start of the visible beam.
    /// /returns Visible lane length after source trimming.
    /// </summary>
    private static float ResolveVisibleLaneLength(DynamicBuffer<PlayerLaserBeamLaneElement> laserBeamLanes,
                                                  int laneSegmentStartIndex,
                                                  int laneSegmentEndIndex,
                                                  float sourceOffset)
    {
        float remainingSourceTrim = math.max(0f, sourceOffset);
        float visibleLaneLength = 0f;

        for (int laneSegmentIndex = laneSegmentStartIndex; laneSegmentIndex < laneSegmentEndIndex; laneSegmentIndex++)
        {
            float segmentLength = math.max(0f, laserBeamLanes[laneSegmentIndex].Length);
            float trimmedDistance = math.min(segmentLength, remainingSourceTrim);
            remainingSourceTrim -= trimmedDistance;
            visibleLaneLength += math.max(0f, segmentLength - trimmedDistance);
        }

        return math.max(0f, visibleLaneLength);
    }

    /// <summary>
    /// Converts one baked linear float4 color into a managed Unity color.
    /// /params value Baked float4 color.
    /// /returns Managed Unity color.
    /// </summary>
    private static Color ToColor(float4 value)
    {
        return new Color(value.x, value.y, value.z, value.w);
    }
    #endregion

    #endregion
}
