using System;
using UnityEngine;

/// <summary>
/// Stores inspector-facing presentation options used by HUDManager to render one liquid HUD bar.
/// /params None.
/// /returns None.
/// </summary>
[Serializable]
public sealed class HUDLiquidBarPresentationSettings
{
    #region Serialized Fields
    [Tooltip("Enables the liquid shader layer for this bar.")]
    [SerializeField] private bool enableLiquidShader = true;

    [Tooltip("Optional material template cloned at runtime for this bar. When left empty, the HUD loads the default referenced material for the bar role.")]
    [SerializeField] private Material liquidMaterialTemplate;

    [Tooltip("Enables the syringe plunger that follows the current fill percentage.")]
    [SerializeField] private bool enablePiston = true;

    [Tooltip("Optional plunger root transform. When left empty, the bar searches its direct children for the first RectTransform whose name contains 'Pointer'.")]
    [SerializeField] private RectTransform pistonRoot;

    [Tooltip("Additional local X offset applied after the plunger position is resolved from the fill image.")]
    [SerializeField] private float pistonLocalOffsetX;

    [Tooltip("Additional local Y offset applied after the plunger position is resolved from the fill image.")]
    [SerializeField] private float pistonLocalOffsetY;

    [Tooltip("Enables a temporary liquid slosh pulse when the target value increases or decreases.")]
    [SerializeField] private bool enableValueDeltaMotion = true;

    [Tooltip("Minimum normalized delta required before the slosh pulse retriggers.")]
    [SerializeField] private float deltaTriggerThreshold = 0.01f;

    [Tooltip("Multiplier applied to the slosh pulse intensity generated by value changes.")]
    [SerializeField] private float deltaMotionStrength = 1f;

    [Tooltip("Seconds used to decay the slosh pulse back to rest. Lower values settle faster.")]
    [SerializeField] private float deltaMotionDecaySeconds = 0.35f;
    #endregion

    #region Properties
    public bool EnableLiquidShader
    {
        get
        {
            return enableLiquidShader;
        }
    }

    public Material LiquidMaterialTemplate
    {
        get
        {
            return liquidMaterialTemplate;
        }
    }

    public bool EnablePiston
    {
        get
        {
            return enablePiston;
        }
    }

    public RectTransform PistonRoot
    {
        get
        {
            return pistonRoot;
        }
    }

    public float PistonLocalOffsetX
    {
        get
        {
            return pistonLocalOffsetX;
        }
    }

    public float PistonLocalOffsetY
    {
        get
        {
            return pistonLocalOffsetY;
        }
    }

    public bool EnableValueDeltaMotion
    {
        get
        {
            return enableValueDeltaMotion;
        }
    }

    public float DeltaTriggerThreshold
    {
        get
        {
            return deltaTriggerThreshold;
        }
    }

    public float DeltaMotionStrength
    {
        get
        {
            return deltaMotionStrength;
        }
    }

    public float DeltaMotionDecaySeconds
    {
        get
        {
            return deltaMotionDecaySeconds;
        }
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Builds default presentation settings tuned for the health syringe bar.
    /// /params None.
    /// /returns Default health-bar presentation settings.
    /// </summary>
    public static HUDLiquidBarPresentationSettings CreateHealthDefaults()
    {
        return new HUDLiquidBarPresentationSettings
        {
            enableLiquidShader = true,
            enablePiston = true,
            enableValueDeltaMotion = true,
            deltaTriggerThreshold = 0.0075f,
            deltaMotionStrength = 1.2f,
            deltaMotionDecaySeconds = 0.42f
        };
    }

    /// <summary>
    /// Builds default presentation settings tuned for the shield syringe bar.
    /// /params None.
    /// /returns Default shield-bar presentation settings.
    /// </summary>
    public static HUDLiquidBarPresentationSettings CreateShieldDefaults()
    {
        return new HUDLiquidBarPresentationSettings
        {
            enableLiquidShader = true,
            enablePiston = true,
            enableValueDeltaMotion = true,
            deltaTriggerThreshold = 0.0065f,
            deltaMotionStrength = 1.15f,
            deltaMotionDecaySeconds = 0.38f
        };
    }

    /// <summary>
    /// Builds default presentation settings tuned for the experience bar.
    /// /params None.
    /// /returns Default experience-bar presentation settings.
    /// </summary>
    public static HUDLiquidBarPresentationSettings CreateExperienceDefaults()
    {
        return new HUDLiquidBarPresentationSettings
        {
            enableLiquidShader = true,
            enablePiston = false,
            enableValueDeltaMotion = true,
            deltaTriggerThreshold = 0.0125f,
            deltaMotionStrength = 0.9f,
            deltaMotionDecaySeconds = 0.3f
        };
    }
    #endregion

    #endregion
}
