using System.Collections.Generic;
using Unity.Entities;
using Unity.Mathematics;
using Unity.Transforms;
using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Presents spawn-warning rings from the live per-enemy warning state generated by spawn reservations.
/// </summary>
[UpdateInGroup(typeof(PresentationSystemGroup))]
public partial struct EnemySpawnWarningPresentationSystem : ISystem
{
    #region Constants
    private const float MinimumFadeDurationSeconds = 0.0001f;
    private const float MinimumLeadDurationSeconds = 0.0001f;
    private const float MinimumRingWidth = 0.01f;
    #endregion

    #region Fields
    private static readonly Dictionary<Entity, EnemySpawnWarningRingView> activeViewByEnemy = new Dictionary<Entity, EnemySpawnWarningRingView>(256);
    private static readonly HashSet<Entity> visibleEnemyEntities = new HashSet<Entity>();
    private static readonly List<Entity> enemyEntitiesPendingRecycle = new List<Entity>(256);
    private static readonly Stack<EnemySpawnWarningRingView> pooledViews = new Stack<EnemySpawnWarningRingView>(128);

    private static GameObject runtimeRootObject;
    private static Material sharedWarningMaterial;
    #endregion

    #region Methods

    #region Lifecycle
    /// <summary>
    /// Requires at least one active warning state before the presentation system starts ticking.
    /// state: Current ECS system state.
    /// returns None.
    /// </summary>
    public void OnCreate(ref SystemState state)
    {
        state.RequireForUpdate<EnemySpawnWarningState>();
    }

    /// <summary>
    /// Renders each currently active spawn-warning ring and recycles views once their warning state expires.
    /// state: Current ECS system state.
    /// returns None.
    /// </summary>
    public void OnUpdate(ref SystemState state)
    {
        EntityManager entityManager = state.EntityManager;
        float elapsedTime = (float)SystemAPI.Time.ElapsedTime;
        visibleEnemyEntities.Clear();

        foreach ((RefRO<EnemySpawnWarningState> warningState,
                  Entity enemyEntity) in SystemAPI.Query<RefRO<EnemySpawnWarningState>>()
                                                 .WithEntityAccess())
        {
            EnemySpawnWarningState currentWarningState = warningState.ValueRO;

            if (ShouldDisableWarningState(in currentWarningState, elapsedTime))
            {
                entityManager.SetComponentEnabled<EnemySpawnWarningState>(enemyEntity, false);
                continue;
            }

            if (!TryResolveWarningVisualState(in currentWarningState,
                                              elapsedTime,
                                              out float opacity,
                                              out float widthScale))
            {
                continue;
            }

            EnemySpawnWarningRingView view = GetOrCreateView(enemyEntity);

            if (view == null)
                continue;

            float3 warningPosition = currentWarningState.WorldPosition;
            Vector3 worldPosition = new Vector3(warningPosition.x,
                                                warningPosition.y + math.max(0f, currentWarningState.HeightOffset),
                                                warningPosition.z);
            Color ringColor = new Color(currentWarningState.Color.x,
                                        currentWarningState.Color.y,
                                        currentWarningState.Color.z,
                                        currentWarningState.Color.w);

            view.Render(worldPosition,
                        currentWarningState.Radius,
                        math.max(MinimumRingWidth, currentWarningState.RingWidth),
                        ringColor,
                        opacity,
                        widthScale);
            visibleEnemyEntities.Add(enemyEntity);
        }

        RecycleHiddenViews();
    }

    /// <summary>
    /// Releases all pooled runtime objects allocated by the warning presentation system.
    /// state: Current ECS system state.
    /// returns None.
    /// </summary>
    public void OnDestroy(ref SystemState state)
    {
        DestroyAllViews();
        DestroySharedMaterial();
        DestroyRuntimeRoot();
    }
    #endregion

    #region Rendering
    /// <summary>
    /// Resolves whether one warning state should be disabled because it can no longer produce visible output.
    /// warningState: Current warning payload stored on the enemy.
    /// elapsedTime: Current elapsed world time.
    /// returns True when the warning state should be disabled immediately, otherwise false.
    /// </summary>
    private static bool ShouldDisableWarningState(in EnemySpawnWarningState warningState, float elapsedTime)
    {
        if (warningState.MaximumAlpha <= 0f)
            return true;

        if (warningState.Radius <= 0f)
            return true;

        if (warningState.RingWidth <= 0f)
            return true;

        return elapsedTime > warningState.FadeOutEndTime;
    }

    /// <summary>
    /// Resolves the live opacity and width scale of one warning at the current frame.
    /// warningState: Current warning payload stored on the enemy.
    /// elapsedTime: Current elapsed world time.
    /// opacity: Resolved output opacity for the current frame.
    /// widthScale: Resolved output width multiplier for the current frame.
    /// returns True when the warning should be visible during this frame, otherwise false.
    /// </summary>
    private static bool TryResolveWarningVisualState(in EnemySpawnWarningState warningState,
                                                     float elapsedTime,
                                                     out float opacity,
                                                     out float widthScale)
    {
        if (elapsedTime < warningState.WarningStartTime || elapsedTime > warningState.FadeOutEndTime)
        {
            opacity = 0f;
            widthScale = 0f;
            return false;
        }

        if (elapsedTime <= warningState.SpawnTime)
        {
            float normalizedProgress = warningState.LeadTimeSeconds <= 0f
                ? 1f
                : math.saturate((elapsedTime - warningState.WarningStartTime) / math.max(MinimumLeadDurationSeconds, warningState.LeadTimeSeconds));
            float smoothedProgress = normalizedProgress * normalizedProgress * (3f - 2f * normalizedProgress);
            opacity = warningState.MaximumAlpha * math.lerp(0.18f, 1f, smoothedProgress);
            widthScale = math.lerp(0.8f, 1.18f, smoothedProgress);
            return true;
        }

        if (warningState.FadeOutSeconds <= 0f)
        {
            opacity = 0f;
            widthScale = 0f;
            return false;
        }

        float normalizedFade = 1f - math.saturate((elapsedTime - warningState.SpawnTime) / math.max(MinimumFadeDurationSeconds, warningState.FadeOutSeconds));
        opacity = warningState.MaximumAlpha * normalizedFade;
        widthScale = math.lerp(0.82f, 1.18f, normalizedFade);
        return opacity > 0f;
    }
    #endregion

    #region View Pool
    /// <summary>
    /// Resolves an existing warning view for the enemy or creates a new pooled one when needed.
    /// enemyEntity: Enemy that currently owns the warning state.
    /// returns Runtime ring view associated with the provided enemy.
    /// </summary>
    private static EnemySpawnWarningRingView GetOrCreateView(Entity enemyEntity)
    {
        if (activeViewByEnemy.TryGetValue(enemyEntity, out EnemySpawnWarningRingView activeView))
            return activeView;

        EnemySpawnWarningRingView view = AcquireView();

        if (view == null)
            return null;

        activeViewByEnemy.Add(enemyEntity, view);
        return view;
    }

    /// <summary>
    /// Returns hidden pooled views back to the free stack once they are no longer visible this frame.
    /// returns None.
    /// </summary>
    private static void RecycleHiddenViews()
    {
        enemyEntitiesPendingRecycle.Clear();

        foreach (KeyValuePair<Entity, EnemySpawnWarningRingView> pair in activeViewByEnemy)
        {
            if (visibleEnemyEntities.Contains(pair.Key) && pair.Value != null)
                continue;

            if (pair.Value != null)
            {
                pair.Value.Deactivate();
                pooledViews.Push(pair.Value);
            }

            enemyEntitiesPendingRecycle.Add(pair.Key);
        }

        for (int entityIndex = 0; entityIndex < enemyEntitiesPendingRecycle.Count; entityIndex++)
            activeViewByEnemy.Remove(enemyEntitiesPendingRecycle[entityIndex]);
    }

    /// <summary>
    /// Acquires one pooled warning ring view or creates a new one when the pool is empty.
    /// returns Runtime warning ring view ready for rendering, or null when creation failed.
    /// </summary>
    private static EnemySpawnWarningRingView AcquireView()
    {
        while (pooledViews.Count > 0)
        {
            EnemySpawnWarningRingView pooledView = pooledViews.Pop();

            if (pooledView == null)
                continue;

            Transform runtimeRootTransform = ResolveRuntimeRootTransform();

            if (pooledView.transform.parent != runtimeRootTransform)
                pooledView.transform.SetParent(runtimeRootTransform, false);

            pooledView.Initialize(ResolveSharedWarningMaterial());
            return pooledView;
        }

        GameObject viewObject = new GameObject("EnemySpawnWarningRingView");
        viewObject.hideFlags = HideFlags.HideAndDontSave;
        Transform createdRootTransform = ResolveRuntimeRootTransform();

        if (createdRootTransform != null)
            viewObject.transform.SetParent(createdRootTransform, false);

        EnemySpawnWarningRingView createdView = viewObject.AddComponent<EnemySpawnWarningRingView>();
        createdView.Initialize(ResolveSharedWarningMaterial());
        createdView.Deactivate();
        return createdView;
    }

    /// <summary>
    /// Destroys every active or pooled warning view immediately.
    /// returns None.
    /// </summary>
    private static void DestroyAllViews()
    {
        foreach (KeyValuePair<Entity, EnemySpawnWarningRingView> pair in activeViewByEnemy)
        {
            if (pair.Value != null)
                Object.DestroyImmediate(pair.Value.gameObject);
        }

        activeViewByEnemy.Clear();

        while (pooledViews.Count > 0)
        {
            EnemySpawnWarningRingView pooledView = pooledViews.Pop();

            if (pooledView == null)
                continue;

            Object.DestroyImmediate(pooledView.gameObject);
        }

        visibleEnemyEntities.Clear();
        enemyEntitiesPendingRecycle.Clear();
    }
    #endregion

    #region Runtime Resources
    /// <summary>
    /// Resolves the hidden runtime root used to parent every pooled warning view.
    /// returns Runtime root transform used by warning views.
    /// </summary>
    private static Transform ResolveRuntimeRootTransform()
    {
        if (runtimeRootObject == null)
        {
            runtimeRootObject = new GameObject("EnemySpawnWarningRuntimeRoot");
            runtimeRootObject.hideFlags = HideFlags.HideAndDontSave;
        }

        return runtimeRootObject.transform;
    }

    /// <summary>
    /// Destroys the hidden runtime root when the system shuts down.
    /// returns None.
    /// </summary>
    private static void DestroyRuntimeRoot()
    {
        if (runtimeRootObject == null)
            return;

        Object.DestroyImmediate(runtimeRootObject);
        runtimeRootObject = null;
    }

    /// <summary>
    /// Resolves the shared material assigned to every pooled LineRenderer.
    /// returns Shared runtime material used by warning views.
    /// </summary>
    private static Material ResolveSharedWarningMaterial()
    {
        if (sharedWarningMaterial != null)
            return sharedWarningMaterial;

        Shader lineShader = Shader.Find("Hidden/Internal-Colored");

        if (lineShader == null)
            lineShader = Shader.Find("Sprites/Default");

        if (lineShader == null)
            return null;

        sharedWarningMaterial = new Material(lineShader);
        sharedWarningMaterial.hideFlags = HideFlags.HideAndDontSave;
        sharedWarningMaterial.name = "EnemySpawnWarningRing_Runtime";
        sharedWarningMaterial.SetInt("_SrcBlend", (int)BlendMode.SrcAlpha);
        sharedWarningMaterial.SetInt("_DstBlend", (int)BlendMode.OneMinusSrcAlpha);
        sharedWarningMaterial.SetInt("_Cull", (int)CullMode.Off);
        sharedWarningMaterial.SetInt("_ZWrite", 0);
        sharedWarningMaterial.SetInt("_ZTest", (int)CompareFunction.Always);
        sharedWarningMaterial.renderQueue = (int)RenderQueue.Transparent + 120;
        return sharedWarningMaterial;
    }

    /// <summary>
    /// Destroys the shared runtime material when the system shuts down.
    /// returns None.
    /// </summary>
    private static void DestroySharedMaterial()
    {
        if (sharedWarningMaterial == null)
            return;

        Object.DestroyImmediate(sharedWarningMaterial);
        sharedWarningMaterial = null;
    }
    #endregion

    #endregion
}
