using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;

/// <summary>
/// Represents a compiled mathematical formula that can be evaluated against scalable stat variables.
///  none.
/// returns void.
/// </summary>
public sealed class PlayerCompiledStatFormula
{
    #region Fields
    private readonly PlayerStatFormulaRpnToken[] rpnTokens;
    private readonly string[] variableNames;
    #endregion

    #region Properties
    public IReadOnlyList<string> VariableNames
    {
        get
        {
            return variableNames;
        }
    }
    #endregion

    #region Constructors
    /// <summary>
    /// Creates a compiled formula container from finalized RPN tokens and discovered variable names.
    ///  rpnTokensValue: Reverse-polish token array generated by the parser.
    ///  variableNamesValue: Distinct variables referenced by the formula.
    /// returns New compiled formula instance.
    /// </summary>
    internal PlayerCompiledStatFormula(PlayerStatFormulaRpnToken[] rpnTokensValue, string[] variableNamesValue)
    {
        rpnTokens = rpnTokensValue;
        variableNames = variableNamesValue;
    }
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Evaluates the compiled formula using the provided variable context.
    /// Used by the scaling engine after one successful compile step.
    ///  thisValue: Value mapped to the reserved [this] variable.
    ///  variableValues: External variable dictionary for named scalable stats.
    ///  result: Computed result when evaluation succeeds.
    ///  errorMessage: Failure reason when evaluation fails.
    /// returns True when formula evaluation succeeded.
    /// </summary>
    public bool TryEvaluate(float thisValue,
                            IReadOnlyDictionary<string, float> variableValues,
                            out float result,
                            out string errorMessage)
    {
        result = thisValue;
        errorMessage = string.Empty;

        if (rpnTokens == null || rpnTokens.Length == 0)
        {
            errorMessage = "Formula has no executable tokens.";
            return false;
        }

        Stack<float> evaluationStack = new Stack<float>(rpnTokens.Length);

        for (int tokenIndex = 0; tokenIndex < rpnTokens.Length; tokenIndex++)
        {
            PlayerStatFormulaRpnToken token = rpnTokens[tokenIndex];

            switch (token.Type)
            {
                case PlayerStatFormulaTokenType.Number:
                    evaluationStack.Push(token.NumberValue);
                    continue;
                case PlayerStatFormulaTokenType.Variable:
                    if (!TryResolveVariableValue(token.TextValue, thisValue, variableValues, out float variableValue))
                    {
                        errorMessage = string.Format(CultureInfo.InvariantCulture, "Unknown variable [{0}].", token.TextValue);
                        return false;
                    }

                    evaluationStack.Push(variableValue);
                    continue;
                case PlayerStatFormulaTokenType.Operator:
                    if (!ApplyOperator(token, evaluationStack, out errorMessage))
                        return false;

                    continue;
                case PlayerStatFormulaTokenType.Function:
                    if (!ApplyFunction(token, evaluationStack, out errorMessage))
                        return false;

                    continue;
            }
        }

        if (evaluationStack.Count != 1)
        {
            errorMessage = "Formula evaluation ended with invalid stack state.";
            return false;
        }

        result = evaluationStack.Pop();
        return true;
    }
    #endregion

    #region Private Methods
    /// <summary>
    /// Resolves one variable value from the reserved [this] symbol or the provided external dictionary.
    ///  variableName: Variable name requested by the evaluator.
    ///  thisValue: Current [this] value.
    ///  variableValues: External variable map.
    ///  variableValue: Resolved numeric value.
    /// returns True when the variable could be resolved.
    /// </summary>
    private static bool TryResolveVariableValue(string variableName,
                                                float thisValue,
                                                IReadOnlyDictionary<string, float> variableValues,
                                                out float variableValue)
    {
        variableValue = 0f;

        if (string.Equals(variableName, PlayerScalableStatNameUtility.ReservedThisName, StringComparison.OrdinalIgnoreCase))
        {
            variableValue = thisValue;
            return true;
        }

        if (variableValues == null)
            return false;

        if (variableValues.TryGetValue(variableName, out variableValue))
            return true;

        foreach (KeyValuePair<string, float> entry in variableValues)
        {
            if (!string.Equals(entry.Key, variableName, StringComparison.OrdinalIgnoreCase))
                continue;

            variableValue = entry.Value;
            return true;
        }

        return false;
    }

    /// <summary>
    /// Applies one operator token to the evaluation stack.
    ///  token: Operator token being executed.
    ///  evaluationStack: Current evaluation stack.
    ///  errorMessage: Failure reason when operands are invalid.
    /// returns True when the operator was applied successfully.
    /// </summary>
    private static bool ApplyOperator(PlayerStatFormulaRpnToken token,
                                      Stack<float> evaluationStack,
                                      out string errorMessage)
    {
        errorMessage = string.Empty;

        if (token.IsUnary)
        {
            if (evaluationStack.Count < 1)
            {
                errorMessage = "Unary operator requires one operand.";
                return false;
            }

            float unaryOperand = evaluationStack.Pop();
            evaluationStack.Push(-unaryOperand);
            return true;
        }

        if (evaluationStack.Count < 2)
        {
            errorMessage = "Binary operator requires two operands.";
            return false;
        }

        float rightOperand = evaluationStack.Pop();
        float leftOperand = evaluationStack.Pop();

        switch (token.OperatorSymbol)
        {
            case '+':
                evaluationStack.Push(leftOperand + rightOperand);
                return true;
            case '-':
                evaluationStack.Push(leftOperand - rightOperand);
                return true;
            case '*':
                evaluationStack.Push(leftOperand * rightOperand);
                return true;
            case '/':
                if (Mathf.Abs(rightOperand) <= 0.000001f)
                {
                    errorMessage = "Division by zero is not allowed.";
                    return false;
                }

                evaluationStack.Push(leftOperand / rightOperand);
                return true;
            case '^':
                evaluationStack.Push(Mathf.Pow(leftOperand, rightOperand));
                return true;
        }

        errorMessage = "Unsupported operator encountered during evaluation.";
        return false;
    }

    /// <summary>
    /// Applies one supported function token to the evaluation stack.
    ///  token: Function token being executed.
    ///  evaluationStack: Current evaluation stack.
    ///  errorMessage: Failure reason when function evaluation fails.
    /// returns True when the function was applied successfully.
    /// </summary>
    private static bool ApplyFunction(PlayerStatFormulaRpnToken token,
                                      Stack<float> evaluationStack,
                                      out string errorMessage)
    {
        errorMessage = string.Empty;

        if (evaluationStack.Count < 1)
        {
            errorMessage = "Function requires one operand.";
            return false;
        }

        float functionOperand = evaluationStack.Pop();

        if (string.Equals(token.TextValue, "log", StringComparison.OrdinalIgnoreCase))
        {
            if (functionOperand <= 0f)
            {
                errorMessage = "log() domain error: operand must be greater than zero.";
                return false;
            }

            evaluationStack.Push(Mathf.Log(functionOperand));
            return true;
        }

        errorMessage = "Unsupported function encountered during evaluation.";
        return false;
    }
    #endregion

    #endregion
}

/// <summary>
/// Represents formula compilation output, including either a compiled formula or an error message.
///  none.
/// returns void.
/// </summary>
public readonly struct PlayerStatFormulaCompileResult
{
    #region Fields
    public readonly bool IsValid;
    public readonly PlayerCompiledStatFormula CompiledFormula;
    public readonly string ErrorMessage;
    #endregion

    #region Constructors
    /// <summary>
    /// Creates a compile result wrapper.
    ///  isValidValue: Compilation success flag.
    ///  compiledFormulaValue: Compiled formula when successful.
    ///  errorMessageValue: Human-readable error message when failed.
    /// returns Initialized compile result struct.
    /// </summary>
    public PlayerStatFormulaCompileResult(bool isValidValue, PlayerCompiledStatFormula compiledFormulaValue, string errorMessageValue)
    {
        IsValid = isValidValue;
        CompiledFormula = compiledFormulaValue;
        ErrorMessage = errorMessageValue;
    }
    #endregion
}
