using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;

/// <summary>
/// Represents a compiled mathematical formula that can be evaluated against scalable stat variables.
/// </summary>
public sealed class PlayerCompiledStatFormula
{
    #region Fields
    private readonly PlayerStatFormulaRpnToken[] rpnTokens;
    private readonly string[] variableNames;
    #endregion

    #region Properties
    public IReadOnlyList<string> VariableNames
    {
        get
        {
            return variableNames;
        }
    }
    #endregion

    #region Constructors
    /// <summary>
    /// Creates a compiled formula container from finalized RPN tokens and discovered variable names.
    /// </summary>
    /// <param name="rpnTokensValue">RPN token array generated by parser.</param>
    /// <param name="variableNamesValue">Distinct variable names detected during compilation.</param>
    /// <returns>New compiled formula instance.</returns>
    internal PlayerCompiledStatFormula(PlayerStatFormulaRpnToken[] rpnTokensValue, string[] variableNamesValue)
    {
        rpnTokens = rpnTokensValue;
        variableNames = variableNamesValue;
    }
    #endregion

    #region Methods

    #region Evaluation
    /// <summary>
    /// Evaluates the compiled formula using the provided variable context.
    /// </summary>
    /// <param name="thisValue">Value mapped to [this] variable.</param>
    /// <param name="variableValues">Dictionary used for non-[this] variable lookup.</param>
    /// <param name="result">Computed result when evaluation succeeds.</param>
    /// <param name="errorMessage">Detailed failure reason when evaluation fails.</param>
    /// <returns>True when formula evaluation succeeded, otherwise false.</returns>
    public bool TryEvaluate(float thisValue,
                            IReadOnlyDictionary<string, float> variableValues,
                            out float result,
                            out string errorMessage)
    {
        result = thisValue;
        errorMessage = string.Empty;

        if (rpnTokens == null || rpnTokens.Length == 0)
        {
            errorMessage = "Formula has no executable tokens.";
            return false;
        }

        Stack<float> evaluationStack = new Stack<float>(rpnTokens.Length);

        for (int tokenIndex = 0; tokenIndex < rpnTokens.Length; tokenIndex++)
        {
            PlayerStatFormulaRpnToken token = rpnTokens[tokenIndex];

            switch (token.Type)
            {
                case PlayerStatFormulaTokenType.Number:
                    evaluationStack.Push(token.NumberValue);
                    continue;
                case PlayerStatFormulaTokenType.Variable:
                    if (TryResolveVariableValue(token.TextValue, thisValue, variableValues, out float variableValue) == false)
                    {
                        errorMessage = string.Format(CultureInfo.InvariantCulture, "Unknown variable [{0}].", token.TextValue);
                        return false;
                    }

                    evaluationStack.Push(variableValue);
                    continue;
                case PlayerStatFormulaTokenType.Operator:
                    if (ApplyOperator(token, evaluationStack, out errorMessage) == false)
                        return false;

                    continue;
                case PlayerStatFormulaTokenType.Function:
                    if (ApplyFunction(token, evaluationStack, out errorMessage) == false)
                        return false;

                    continue;
            }
        }

        if (evaluationStack.Count != 1)
        {
            errorMessage = "Formula evaluation ended with invalid stack state.";
            return false;
        }

        result = evaluationStack.Pop();
        return true;
    }

    private static bool TryResolveVariableValue(string variableName,
                                                float thisValue,
                                                IReadOnlyDictionary<string, float> variableValues,
                                                out float variableValue)
    {
        variableValue = 0f;

        if (string.Equals(variableName, PlayerScalableStatNameUtility.ReservedThisName, StringComparison.OrdinalIgnoreCase))
        {
            variableValue = thisValue;
            return true;
        }

        if (variableValues == null)
            return false;

        if (variableValues.TryGetValue(variableName, out variableValue))
            return true;

        foreach (KeyValuePair<string, float> entry in variableValues)
        {
            if (string.Equals(entry.Key, variableName, StringComparison.OrdinalIgnoreCase) == false)
                continue;

            variableValue = entry.Value;
            return true;
        }

        return false;
    }

    private static bool ApplyOperator(PlayerStatFormulaRpnToken token,
                                      Stack<float> evaluationStack,
                                      out string errorMessage)
    {
        errorMessage = string.Empty;

        if (token.IsUnary)
        {
            if (evaluationStack.Count < 1)
            {
                errorMessage = "Unary operator requires one operand.";
                return false;
            }

            float unaryOperand = evaluationStack.Pop();
            evaluationStack.Push(-unaryOperand);
            return true;
        }

        if (evaluationStack.Count < 2)
        {
            errorMessage = "Binary operator requires two operands.";
            return false;
        }

        float rightOperand = evaluationStack.Pop();
        float leftOperand = evaluationStack.Pop();

        switch (token.OperatorSymbol)
        {
            case '+':
                evaluationStack.Push(leftOperand + rightOperand);
                return true;
            case '-':
                evaluationStack.Push(leftOperand - rightOperand);
                return true;
            case '*':
                evaluationStack.Push(leftOperand * rightOperand);
                return true;
            case '/':
                if (Mathf.Abs(rightOperand) <= 0.000001f)
                {
                    errorMessage = "Division by zero is not allowed.";
                    return false;
                }

                evaluationStack.Push(leftOperand / rightOperand);
                return true;
            case '^':
                evaluationStack.Push(Mathf.Pow(leftOperand, rightOperand));
                return true;
        }

        errorMessage = "Unsupported operator encountered during evaluation.";
        return false;
    }

    private static bool ApplyFunction(PlayerStatFormulaRpnToken token,
                                      Stack<float> evaluationStack,
                                      out string errorMessage)
    {
        errorMessage = string.Empty;

        if (evaluationStack.Count < 1)
        {
            errorMessage = "Function requires one operand.";
            return false;
        }

        float functionOperand = evaluationStack.Pop();

        if (string.Equals(token.TextValue, "log", StringComparison.OrdinalIgnoreCase))
        {
            if (functionOperand <= 0f)
            {
                errorMessage = "log() domain error: operand must be greater than zero.";
                return false;
            }

            evaluationStack.Push(Mathf.Log(functionOperand));
            return true;
        }

        errorMessage = "Unsupported function encountered during evaluation.";
        return false;
    }
    #endregion

    #endregion
}

/// <summary>
/// Represents formula compilation output, including either a compiled formula or an error message.
/// </summary>
public readonly struct PlayerStatFormulaCompileResult
{
    #region Fields
    public readonly bool IsValid;
    public readonly PlayerCompiledStatFormula CompiledFormula;
    public readonly string ErrorMessage;
    #endregion

    #region Constructors
    /// <summary>
    /// Creates a compile result wrapper.
    /// </summary>
    /// <param name="isValidValue">Compilation success flag.</param>
    /// <param name="compiledFormulaValue">Compiled formula when successful.</param>
    /// <param name="errorMessageValue">Human-readable error message when failed.</param>
    /// <returns>Initialized compile result struct.</returns>
    public PlayerStatFormulaCompileResult(bool isValidValue, PlayerCompiledStatFormula compiledFormulaValue, string errorMessageValue)
    {
        IsValid = isValidValue;
        CompiledFormula = compiledFormulaValue;
        ErrorMessage = errorMessageValue;
    }
    #endregion
}

/// <summary>
/// Provides parsing, compilation, and cached lookup for player scaling formulas.
/// </summary>
public static class PlayerStatFormulaEngine
{
    #region Fields
    private static readonly Dictionary<string, PlayerStatFormulaCompileResult> compileCache = new Dictionary<string, PlayerStatFormulaCompileResult>(StringComparer.Ordinal);
    #endregion

    #region Methods

    #region Public Methods
    /// <summary>
    /// Compiles a formula string to an executable token graph.
    /// </summary>
    /// <param name="formula">Formula string using [variables], operators, parentheses and log().</param>
    /// <param name="requireAtLeastOneVariable">When true, formulas with no variable tokens are rejected.</param>
    /// <returns>Compilation result containing either a compiled formula or an error.</returns>
    public static PlayerStatFormulaCompileResult Compile(string formula, bool requireAtLeastOneVariable)
    {
        string normalizedFormula = string.IsNullOrWhiteSpace(formula) ? string.Empty : formula.Trim();
        string cacheKey = string.Format(CultureInfo.InvariantCulture, "{0}|{1}", requireAtLeastOneVariable ? "1" : "0", normalizedFormula);

        if (compileCache.TryGetValue(cacheKey, out PlayerStatFormulaCompileResult cachedResult))
            return cachedResult;

        PlayerStatFormulaCompileResult compileResult = CompileInternal(normalizedFormula, requireAtLeastOneVariable);
        compileCache[cacheKey] = compileResult;
        return compileResult;
    }

    /// <summary>
    /// Evaluates a raw formula string directly, compiling it on first use.
    /// </summary>
    /// <param name="formula">Formula expression to evaluate.</param>
    /// <param name="thisValue">Value mapped to [this].</param>
    /// <param name="variableValues">Variable dictionary for named scalable stats.</param>
    /// <param name="result">Computed result when evaluation succeeds.</param>
    /// <param name="errorMessage">Failure reason when evaluation fails.</param>
    /// <returns>True when evaluation succeeded, otherwise false.</returns>
    public static bool TryEvaluate(string formula,
                                   float thisValue,
                                   IReadOnlyDictionary<string, float> variableValues,
                                   out float result,
                                   out string errorMessage)
    {
        PlayerStatFormulaCompileResult compileResult = Compile(formula, true);

        if (compileResult.IsValid == false || compileResult.CompiledFormula == null)
        {
            result = thisValue;
            errorMessage = compileResult.ErrorMessage;
            return false;
        }

        return compileResult.CompiledFormula.TryEvaluate(thisValue, variableValues, out result, out errorMessage);
    }
    #endregion

    #region Compilation
    private static PlayerStatFormulaCompileResult CompileInternal(string formula, bool requireAtLeastOneVariable)
    {
        if (string.IsNullOrWhiteSpace(formula))
            return new PlayerStatFormulaCompileResult(false, null, "Formula is empty.");

        if (Tokenize(formula, out List<PlayerStatFormulaToken> tokens, out string tokenizationError) == false)
            return new PlayerStatFormulaCompileResult(false, null, tokenizationError);

        if (BuildRpn(tokens, out List<PlayerStatFormulaRpnToken> rpnTokens, out HashSet<string> variableNames, out string parseError) == false)
            return new PlayerStatFormulaCompileResult(false, null, parseError);

        if (requireAtLeastOneVariable && variableNames.Count == 0)
            return new PlayerStatFormulaCompileResult(false, null, "Formula must reference at least one variable ([this] or [StatName]).");

        if (ValidateRpnStructure(rpnTokens, out string structureError) == false)
            return new PlayerStatFormulaCompileResult(false, null, structureError);

        string[] variableNamesArray = new string[variableNames.Count];
        variableNames.CopyTo(variableNamesArray);
        PlayerCompiledStatFormula compiledFormula = new PlayerCompiledStatFormula(rpnTokens.ToArray(), variableNamesArray);
        return new PlayerStatFormulaCompileResult(true, compiledFormula, string.Empty);
    }

    private static bool Tokenize(string formula,
                                 out List<PlayerStatFormulaToken> tokens,
                                 out string errorMessage)
    {
        tokens = new List<PlayerStatFormulaToken>();
        errorMessage = string.Empty;
        int index = 0;

        while (index < formula.Length)
        {
            char currentCharacter = formula[index];

            if (char.IsWhiteSpace(currentCharacter))
            {
                index += 1;
                continue;
            }

            if (currentCharacter == '[')
            {
                int closingBracketIndex = formula.IndexOf(']', index + 1);

                if (closingBracketIndex < 0)
                {
                    errorMessage = "Variable token is missing closing ']'.";
                    return false;
                }

                string variableName = formula.Substring(index + 1, closingBracketIndex - index - 1).Trim();

                if (string.IsNullOrWhiteSpace(variableName))
                {
                    errorMessage = "Variable token cannot be empty.";
                    return false;
                }

                tokens.Add(PlayerStatFormulaToken.CreateVariable(variableName));
                index = closingBracketIndex + 1;
                continue;
            }

            if (IsNumberStart(formula, index))
            {
                if (TryReadNumberToken(formula, ref index, out float numberValue) == false)
                {
                    errorMessage = "Invalid number literal in formula.";
                    return false;
                }

                tokens.Add(PlayerStatFormulaToken.CreateNumber(numberValue));
                continue;
            }

            if (IsOperator(currentCharacter))
            {
                tokens.Add(PlayerStatFormulaToken.CreateOperator(currentCharacter, false));
                index += 1;
                continue;
            }

            if (currentCharacter == '(')
            {
                tokens.Add(PlayerStatFormulaToken.CreateParenthesis(true));
                index += 1;
                continue;
            }

            if (currentCharacter == ')')
            {
                tokens.Add(PlayerStatFormulaToken.CreateParenthesis(false));
                index += 1;
                continue;
            }

            if (char.IsLetter(currentCharacter))
            {
                int identifierStartIndex = index;

                while (index < formula.Length && char.IsLetter(formula[index]))
                    index += 1;

                string identifier = formula.Substring(identifierStartIndex, index - identifierStartIndex);

                if (string.Equals(identifier, "log", StringComparison.OrdinalIgnoreCase) == false)
                {
                    errorMessage = string.Format(CultureInfo.InvariantCulture, "Unsupported identifier '{0}'.", identifier);
                    return false;
                }

                int lookAheadIndex = index;

                while (lookAheadIndex < formula.Length && char.IsWhiteSpace(formula[lookAheadIndex]))
                    lookAheadIndex += 1;

                if (lookAheadIndex >= formula.Length || formula[lookAheadIndex] != '(')
                {
                    errorMessage = "Function log must be followed by parentheses.";
                    return false;
                }

                tokens.Add(PlayerStatFormulaToken.CreateFunction("log"));
                continue;
            }

            errorMessage = string.Format(CultureInfo.InvariantCulture, "Unsupported character '{0}' in formula.", currentCharacter);
            return false;
        }

        if (tokens.Count == 0)
        {
            errorMessage = "Formula produced no tokens.";
            return false;
        }

        return true;
    }

    private static bool BuildRpn(List<PlayerStatFormulaToken> tokens,
                                 out List<PlayerStatFormulaRpnToken> rpnTokens,
                                 out HashSet<string> variableNames,
                                 out string errorMessage)
    {
        rpnTokens = new List<PlayerStatFormulaRpnToken>(tokens.Count);
        variableNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        errorMessage = string.Empty;
        Stack<PlayerStatFormulaToken> operatorStack = new Stack<PlayerStatFormulaToken>();
        PlayerStatFormulaToken? previousToken = null;

        for (int tokenIndex = 0; tokenIndex < tokens.Count; tokenIndex++)
        {
            PlayerStatFormulaToken currentToken = tokens[tokenIndex];

            switch (currentToken.Type)
            {
                case PlayerStatFormulaTokenType.Number:
                    rpnTokens.Add(PlayerStatFormulaRpnToken.CreateNumber(currentToken.NumberValue));
                    previousToken = currentToken;
                    continue;
                case PlayerStatFormulaTokenType.Variable:
                    variableNames.Add(currentToken.TextValue);
                    rpnTokens.Add(PlayerStatFormulaRpnToken.CreateVariable(currentToken.TextValue));
                    previousToken = currentToken;
                    continue;
                case PlayerStatFormulaTokenType.Function:
                    operatorStack.Push(currentToken);
                    previousToken = currentToken;
                    continue;
                case PlayerStatFormulaTokenType.LeftParenthesis:
                    operatorStack.Push(currentToken);
                    previousToken = currentToken;
                    continue;
                case PlayerStatFormulaTokenType.RightParenthesis:
                    if (PopUntilLeftParenthesis(operatorStack, rpnTokens, out errorMessage) == false)
                        return false;

                    if (operatorStack.Count > 0 && operatorStack.Peek().Type == PlayerStatFormulaTokenType.Function)
                    {
                        PlayerStatFormulaToken functionToken = operatorStack.Pop();
                        rpnTokens.Add(PlayerStatFormulaRpnToken.CreateFunction(functionToken.TextValue));
                    }

                    previousToken = currentToken;
                    continue;
                case PlayerStatFormulaTokenType.Operator:
                    PlayerStatFormulaToken resolvedOperator = ResolveOperatorToken(currentToken, previousToken);

                    while (operatorStack.Count > 0 && ShouldPopOperator(operatorStack.Peek(), resolvedOperator))
                    {
                        PlayerStatFormulaToken poppedOperator = operatorStack.Pop();
                        rpnTokens.Add(PlayerStatFormulaRpnToken.FromOperatorToken(poppedOperator));
                    }

                    operatorStack.Push(resolvedOperator);
                    previousToken = resolvedOperator;
                    continue;
            }
        }

        while (operatorStack.Count > 0)
        {
            PlayerStatFormulaToken stackToken = operatorStack.Pop();

            if (stackToken.Type == PlayerStatFormulaTokenType.LeftParenthesis || stackToken.Type == PlayerStatFormulaTokenType.RightParenthesis)
            {
                errorMessage = "Mismatched parentheses in formula.";
                return false;
            }

            if (stackToken.Type == PlayerStatFormulaTokenType.Function)
            {
                rpnTokens.Add(PlayerStatFormulaRpnToken.CreateFunction(stackToken.TextValue));
                continue;
            }

            rpnTokens.Add(PlayerStatFormulaRpnToken.FromOperatorToken(stackToken));
        }

        return true;
    }

    private static bool ValidateRpnStructure(List<PlayerStatFormulaRpnToken> rpnTokens, out string errorMessage)
    {
        errorMessage = string.Empty;
        int depth = 0;

        for (int index = 0; index < rpnTokens.Count; index++)
        {
            PlayerStatFormulaRpnToken token = rpnTokens[index];

            switch (token.Type)
            {
                case PlayerStatFormulaTokenType.Number:
                case PlayerStatFormulaTokenType.Variable:
                    depth += 1;
                    continue;
                case PlayerStatFormulaTokenType.Function:
                    if (depth < 1)
                    {
                        errorMessage = "Function has no operand.";
                        return false;
                    }

                    continue;
                case PlayerStatFormulaTokenType.Operator:
                    if (token.IsUnary)
                    {
                        if (depth < 1)
                        {
                            errorMessage = "Unary operator has no operand.";
                            return false;
                        }

                        continue;
                    }

                    if (depth < 2)
                    {
                        errorMessage = "Binary operator has insufficient operands.";
                        return false;
                    }

                    depth -= 1;
                    continue;
            }
        }

        if (depth != 1)
        {
            errorMessage = "Formula expression is incomplete.";
            return false;
        }

        return true;
    }
    #endregion

    #region Token Helpers
    private static bool IsNumberStart(string formula, int index)
    {
        if (index < 0 || index >= formula.Length)
            return false;

        char currentCharacter = formula[index];

        if (char.IsDigit(currentCharacter))
            return true;

        if (currentCharacter == '.')
        {
            int nextIndex = index + 1;

            if (nextIndex < formula.Length && char.IsDigit(formula[nextIndex]))
                return true;
        }

        return false;
    }

    private static bool TryReadNumberToken(string formula, ref int index, out float value)
    {
        value = 0f;
        int startIndex = index;
        bool hasDecimalSeparator = false;

        while (index < formula.Length)
        {
            char currentCharacter = formula[index];

            if (char.IsDigit(currentCharacter))
            {
                index += 1;
                continue;
            }

            if (currentCharacter == '.')
            {
                if (hasDecimalSeparator)
                    return false;

                hasDecimalSeparator = true;
                index += 1;
                continue;
            }

            break;
        }

        string numberToken = formula.Substring(startIndex, index - startIndex);

        if (float.TryParse(numberToken, NumberStyles.Float, CultureInfo.InvariantCulture, out value) == false)
            return false;

        return true;
    }

    private static bool IsOperator(char character)
    {
        if (character == '+')
            return true;

        if (character == '-')
            return true;

        if (character == '*')
            return true;

        if (character == '/')
            return true;

        return character == '^';
    }

    private static PlayerStatFormulaToken ResolveOperatorToken(PlayerStatFormulaToken token, PlayerStatFormulaToken? previousToken)
    {
        if (token.OperatorSymbol != '-')
            return token;

        if (previousToken.HasValue == false)
            return PlayerStatFormulaToken.CreateOperator('-', true);

        PlayerStatFormulaTokenType previousType = previousToken.Value.Type;

        if (previousType == PlayerStatFormulaTokenType.Operator)
            return PlayerStatFormulaToken.CreateOperator('-', true);

        if (previousType == PlayerStatFormulaTokenType.LeftParenthesis)
            return PlayerStatFormulaToken.CreateOperator('-', true);

        if (previousType == PlayerStatFormulaTokenType.Function)
            return PlayerStatFormulaToken.CreateOperator('-', true);

        return token;
    }

    private static bool ShouldPopOperator(PlayerStatFormulaToken stackToken, PlayerStatFormulaToken currentToken)
    {
        if (stackToken.Type == PlayerStatFormulaTokenType.Function)
            return true;

        if (stackToken.Type != PlayerStatFormulaTokenType.Operator)
            return false;

        int stackPrecedence = GetPrecedence(stackToken);
        int currentPrecedence = GetPrecedence(currentToken);

        if (stackPrecedence > currentPrecedence)
            return true;

        if (stackPrecedence < currentPrecedence)
            return false;

        if (currentToken.IsUnary)
            return false;

        if (currentToken.OperatorSymbol == '^')
            return false;

        return true;
    }

    private static int GetPrecedence(PlayerStatFormulaToken token)
    {
        if (token.Type != PlayerStatFormulaTokenType.Operator)
            return 0;

        if (token.IsUnary)
            return 4;

        switch (token.OperatorSymbol)
        {
            case '^':
                return 3;
            case '*':
            case '/':
                return 2;
            case '+':
            case '-':
                return 1;
        }

        return 0;
    }

    private static bool PopUntilLeftParenthesis(Stack<PlayerStatFormulaToken> operatorStack,
                                                List<PlayerStatFormulaRpnToken> rpnTokens,
                                                out string errorMessage)
    {
        errorMessage = string.Empty;

        while (operatorStack.Count > 0)
        {
            PlayerStatFormulaToken stackToken = operatorStack.Pop();

            if (stackToken.Type == PlayerStatFormulaTokenType.LeftParenthesis)
                return true;

            if (stackToken.Type == PlayerStatFormulaTokenType.Function)
            {
                rpnTokens.Add(PlayerStatFormulaRpnToken.CreateFunction(stackToken.TextValue));
                continue;
            }

            rpnTokens.Add(PlayerStatFormulaRpnToken.FromOperatorToken(stackToken));
        }

        errorMessage = "Mismatched parentheses in formula.";
        return false;
    }
    #endregion

    #endregion
}

internal enum PlayerStatFormulaTokenType
{
    Number = 0,
    Variable = 1,
    Operator = 2,
    Function = 3,
    LeftParenthesis = 4,
    RightParenthesis = 5
}

internal readonly struct PlayerStatFormulaToken
{
    #region Fields
    public readonly PlayerStatFormulaTokenType Type;
    public readonly float NumberValue;
    public readonly string TextValue;
    public readonly char OperatorSymbol;
    public readonly bool IsUnary;
    #endregion

    #region Constructors
    private PlayerStatFormulaToken(PlayerStatFormulaTokenType type,
                                   float numberValue,
                                   string textValue,
                                   char operatorSymbol,
                                   bool isUnary)
    {
        Type = type;
        NumberValue = numberValue;
        TextValue = textValue;
        OperatorSymbol = operatorSymbol;
        IsUnary = isUnary;
    }
    #endregion

    #region Methods
    public static PlayerStatFormulaToken CreateNumber(float numberValue)
    {
        return new PlayerStatFormulaToken(PlayerStatFormulaTokenType.Number, numberValue, string.Empty, '\0', false);
    }

    public static PlayerStatFormulaToken CreateVariable(string textValue)
    {
        return new PlayerStatFormulaToken(PlayerStatFormulaTokenType.Variable, 0f, textValue, '\0', false);
    }

    public static PlayerStatFormulaToken CreateOperator(char operatorSymbol, bool isUnary)
    {
        return new PlayerStatFormulaToken(PlayerStatFormulaTokenType.Operator, 0f, string.Empty, operatorSymbol, isUnary);
    }

    public static PlayerStatFormulaToken CreateFunction(string textValue)
    {
        return new PlayerStatFormulaToken(PlayerStatFormulaTokenType.Function, 0f, textValue, '\0', false);
    }

    public static PlayerStatFormulaToken CreateParenthesis(bool isLeft)
    {
        PlayerStatFormulaTokenType type = isLeft ? PlayerStatFormulaTokenType.LeftParenthesis : PlayerStatFormulaTokenType.RightParenthesis;
        return new PlayerStatFormulaToken(type, 0f, string.Empty, '\0', false);
    }
    #endregion
}

internal readonly struct PlayerStatFormulaRpnToken
{
    #region Fields
    public readonly PlayerStatFormulaTokenType Type;
    public readonly float NumberValue;
    public readonly string TextValue;
    public readonly char OperatorSymbol;
    public readonly bool IsUnary;
    #endregion

    #region Constructors
    private PlayerStatFormulaRpnToken(PlayerStatFormulaTokenType type,
                                      float numberValue,
                                      string textValue,
                                      char operatorSymbol,
                                      bool isUnary)
    {
        Type = type;
        NumberValue = numberValue;
        TextValue = textValue;
        OperatorSymbol = operatorSymbol;
        IsUnary = isUnary;
    }
    #endregion

    #region Methods
    public static PlayerStatFormulaRpnToken CreateNumber(float numberValue)
    {
        return new PlayerStatFormulaRpnToken(PlayerStatFormulaTokenType.Number, numberValue, string.Empty, '\0', false);
    }

    public static PlayerStatFormulaRpnToken CreateVariable(string textValue)
    {
        return new PlayerStatFormulaRpnToken(PlayerStatFormulaTokenType.Variable, 0f, textValue, '\0', false);
    }

    public static PlayerStatFormulaRpnToken CreateFunction(string textValue)
    {
        return new PlayerStatFormulaRpnToken(PlayerStatFormulaTokenType.Function, 0f, textValue, '\0', false);
    }

    public static PlayerStatFormulaRpnToken FromOperatorToken(PlayerStatFormulaToken token)
    {
        return new PlayerStatFormulaRpnToken(PlayerStatFormulaTokenType.Operator, 0f, string.Empty, token.OperatorSymbol, token.IsUnary);
    }
    #endregion
}
