using UnityEditor;
using UnityEditor.UIElements;
using UnityEngine.UIElements;

/// <summary>
/// Draws the combo-counter HUD section and exposes warnings for missing authored bindings.
/// none.
/// returns none.
/// </summary>
[CustomPropertyDrawer(typeof(HUDComboCounterSection))]
public sealed class HUDComboCounterSectionPropertyDrawer : PropertyDrawer
{
    #region Methods

    #region Public Methods
    /// <summary>
    /// Builds the UI Toolkit inspector for the combo-counter HUD section.
    /// property Serialized combo-counter HUD section property.
    /// returns Root UI element used by the inspector.
    /// </summary>
    public override VisualElement CreatePropertyGUI(SerializedProperty property)
    {
        VisualElement root = new VisualElement();
        SerializedProperty isEnabledProperty = property.FindPropertyRelative("isEnabled");
        SerializedProperty rootObjectProperty = property.FindPropertyRelative("rootObject");
        SerializedProperty rankBadgeImageProperty = property.FindPropertyRelative("rankBadgeImage");
        SerializedProperty rankTextProperty = property.FindPropertyRelative("rankText");
        SerializedProperty comboValueTextProperty = property.FindPropertyRelative("comboValueText");
        SerializedProperty progressFillImageProperty = property.FindPropertyRelative("progressFillImage");
        SerializedProperty progressBackgroundImageProperty = property.FindPropertyRelative("progressBackgroundImage");
        SerializedProperty rankVisualsProperty = property.FindPropertyRelative("rankVisuals");

        if (isEnabledProperty == null ||
            rootObjectProperty == null ||
            rankBadgeImageProperty == null ||
            rankTextProperty == null ||
            comboValueTextProperty == null ||
            progressFillImageProperty == null ||
            progressBackgroundImageProperty == null ||
            rankVisualsProperty == null)
        {
            HelpBox missingHelpBox = new HelpBox("Combo counter HUD section fields are missing.", HelpBoxMessageType.Warning);
            root.Add(missingHelpBox);
            return root;
        }

        HelpBox infoBox = new HelpBox("Assign the top-right combo HUD hierarchy generated by the gameplay integration setup. Rank visuals are keyed by combo Rank ID.", HelpBoxMessageType.Info);
        root.Add(infoBox);
        root.Add(CreateBoundField(isEnabledProperty, "Enabled"));
        root.Add(CreateBoundField(rootObjectProperty, "Root Object"));
        root.Add(CreateBoundField(rankBadgeImageProperty, "Rank Badge Image"));
        root.Add(CreateBoundField(rankTextProperty, "Rank Text"));
        root.Add(CreateBoundField(comboValueTextProperty, "Combo Value Text"));
        root.Add(CreateBoundField(progressFillImageProperty, "Progress Fill Image"));
        root.Add(CreateBoundField(progressBackgroundImageProperty, "Progress Background Image"));
        root.Add(CreateBoundField(property.FindPropertyRelative("defaultBadgeSprite"), "Default Badge Sprite"));
        root.Add(CreateBoundField(property.FindPropertyRelative("defaultBadgeTint"), "Default Badge Tint"));
        root.Add(CreateBoundField(property.FindPropertyRelative("defaultRankTextColor"), "Default Rank Text Color"));
        root.Add(CreateBoundField(property.FindPropertyRelative("defaultComboValueTextColor"), "Default Combo Value Text Color"));
        root.Add(CreateBoundField(property.FindPropertyRelative("defaultProgressFillColor"), "Default Progress Fill Color"));
        root.Add(CreateBoundField(property.FindPropertyRelative("defaultProgressBackgroundColor"), "Default Progress Background Color"));
        root.Add(CreateBoundField(property.FindPropertyRelative("showRankBadgeImage"), "Show Rank Badge Image"));
        root.Add(CreateBoundField(property.FindPropertyRelative("showProgressBar"), "Show Progress Bar"));
        root.Add(CreateBoundField(property.FindPropertyRelative("hideWhenPlayerMissing"), "Hide When Player Missing"));
        root.Add(CreateBoundField(property.FindPropertyRelative("hideWhenZeroCombo"), "Hide When Zero Combo"));
        root.Add(CreateBoundField(property.FindPropertyRelative("idleRankLabel"), "Idle Rank Label"));
        root.Add(CreateBoundField(rankVisualsProperty, "Rank Visuals"));

        HelpBox warningBox = new HelpBox(string.Empty, HelpBoxMessageType.Warning);
        root.Add(warningBox);

        void RefreshWarnings()
        {
            bool hasAnyVisualBinding = rootObjectProperty.objectReferenceValue != null ||
                                       rankTextProperty.objectReferenceValue != null ||
                                       comboValueTextProperty.objectReferenceValue != null;
            bool hasProgressBinding = progressFillImageProperty.objectReferenceValue != null;

            if (!hasAnyVisualBinding)
            {
                warningBox.text = "Assign at least a Root Object or the Rank/Combo TMP texts so the combo HUD can be rendered.";
                warningBox.style.display = DisplayStyle.Flex;
                return;
            }

            if (progressBackgroundImageProperty.objectReferenceValue == null && progressFillImageProperty.objectReferenceValue != null)
            {
                warningBox.text = "Progress Fill Image is assigned without a Progress Background Image.";
                warningBox.style.display = DisplayStyle.Flex;
                return;
            }

            if (!hasProgressBinding)
            {
                warningBox.text = "Progress Fill Image is missing. The combo HUD can still render rank and value, but it cannot show next-rank progress.";
                warningBox.style.display = DisplayStyle.Flex;
                return;
            }

            warningBox.text = string.Empty;
            warningBox.style.display = DisplayStyle.None;
        }

        root.RegisterCallback<SerializedPropertyChangeEvent>(_ => RefreshWarnings());
        RefreshWarnings();
        return root;
    }
    #endregion

    #region Private Methods
    /// <summary>
    /// Creates one bound property field with the requested display label.
    /// property Serialized property bound to the field.
    /// label Inspector label shown for the bound field.
    /// returns Configured property field bound to the serialized property.
    /// </summary>
    private static PropertyField CreateBoundField(SerializedProperty property, string label)
    {
        PropertyField propertyField = new PropertyField(property, label);
        propertyField.BindProperty(property);
        return propertyField;
    }
    #endregion

    #endregion
}
